### ISSUE TITLE
Integer array test

### ISSUE THREAD

**Issue by teivah** [vudangngoc/java-benchmark#2]
Thanks for your DZone post. Yet, I'm not sure to agree with the Integer array test. 

For me, most of the time spent with the Integer array test is done on unboxing the Integers. 

Indeed, if I modify your test (still with 10240000 elements) to have an `Integer result` and do `result = state.data2[i]`, it's even faster than the int array test. So it's not related to CPU cache lines in my humble opinion.

**Comment by vudangngoc** [comment]
Thank you for your comment. I modify the test to check how iteration and object unboxing impact to total running time

`       @Benchmark`
`	@BenchmarkMode(Mode.AverageTime)`
`	@OutputTimeUnit(TimeUnit.NANOSECONDS)`
`	public int iterationOverArrayOfObjects(BenchMarkState state){`
`		Integer result = 0;`
`		for(int i = 0; i < state.size; i++) {`
`			result = state.data2[i];`
`		}`
`		return result.intValue();`
`	}`
`	@Benchmark`
`	@BenchmarkMode(Mode.AverageTime)`
`	@OutputTimeUnit(TimeUnit.NANOSECONDS)`
`	public int unboxingObject(BenchMarkState state){`
`		int result = 0;`
`		for(int i = 0; i < state.size; i++) {`
`			result = state.data2[0].intValue();`
`		}`
`		return result;`
`	}`
`	@Benchmark`
`	@BenchmarkMode(Mode.AverageTime)`
`	@OutputTimeUnit(TimeUnit.NANOSECONDS)`
`	public int iterationAndUnboxing(BenchMarkState state){`
`		int result = 0;`
`		for(int i = 0; i < state.size; i++) {`
`			result = state.data2[i].intValue();`
`		}`
`		return result;`
`	}`

Then I run the test again, we can see that time for unboxing is insignificant 
`Benchmark                                    Mode  Cnt        Score       Error  Units`
`TestObjectArray.iterationAndUnboxing         avgt  200  3964406.452 ± 80727.818  ns/op`
`TestObjectArray.iterationOverArrayOfObjects  avgt  200   422927.826 ±  3977.014  ns/op`
`TestObjectArray.unboxingObject               avgt  200        3.283 ±     0.013  ns/op`
(I run with my laptop, so that the result is different with information in the article on Dzone)

**Comment by teivah** [comment]
Mmh it's not exactly the tests I proposed.

What if you run exactly this:

```java
@Benchmark
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Fork(value = 1, warmups = 3)
@Warmup(iterations = 3)
@Measurement(iterations = 3)
public int intArray(BenchMarkState state){
	int result = 0;
	for(int i = 0; i < state.size; i++) {
		result = state.data1[i];
	}
	return result;
}

@Benchmark
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Fork(value = 1, warmups = 3)
@Warmup(iterations = 3)
@Measurement(iterations = 3)
public int integerArray(BenchMarkState state){
	Integer result = 0;
	for(int i = 0; i < state.size; i++) {
		result = state.data2[i];
	}
	return result;
}
```

What do you get?

**Comment by vudangngoc** [comment]
I see that Integer array is slightly faster than int array. But what I would like to mention is the time of unboxing from Integer to int doesn't take account to the result of Integer array in the original test.

**Comment by teivah** [comment]
I'm not sure to understand what you are trying to prove by accessing always the same element. You don't iterate anymore over the array so it's pointless to compare with the others in my opinion.

For me, the test I copied does prove that there is no real difference in accessing an `int[]` vs accessing an `Integer[]`. Do you share this opinion?

**Comment by vudangngoc** [comment]
I try to access only one item to test time consuming of unboxing from Integer to int (call function Integer.intValue()).
I agree with you that if we access memory of array itself, there is no much different between Integer[] and int[]. But when we access the data that point by a referent of an array, we can access to a memory region that isn't loaded to CPU cache. So that this action will slow.
And I don't know understand the scenario that if size of array is small (less than 16 items), Integer[] is faster than int[].

**Comment by teivah** [comment]
> I agree with you that if we access memory of array itself, there is no much different between Integer[] and int[].

And the `Integer[]` test is faster as we are doing a simple reference copy compared to the `int[]` where we copy the value that's why it's faster. But still, there is no difference between accessing an `Integer` array and an `int` array.

> And I don't know understand the scenario that if size of array is small (less than 16 items), Integer[] is faster than int[].

Again in my humble opinion, it is not related at all to CPU caches but rather than how the JVM does optimize the code when it has been warmed up. Look at the difference if you set `size` to 16 as a `final` field. Accessing the `int[]` in this case is about two times faster than accessing the `Integer[]`. So maybe an optimization done by the JVM as well in the second case?

Yet, I'm not able to see it in my local environment:
```
Benchmark                     Mode  Cnt  Score   Error  Units
TestObjectArray.intArray      avgt    3  9.916 ± 1.107  ns/op
TestObjectArray.integerArray  avgt    3  7.724 ± 2.197  ns/op
```
The error margin is bigger in the second case so it means we could really have the same latency in both cases.
